nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^https?://localhost(:[0-9]+)?$', '^https?://magi.localhost$', '%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'X-CSRF-TOKEN']
        allow_credentials: true
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/login':
            allow_origin: ['^https?://localhost(:[0-9]+)?$', '^https?://magi.localhost$']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'X-CSRF-TOKEN']
            allow_methods: ['POST', 'OPTIONS']
            max_age: 3600
        '^/': # Couvre le reste des routes, adapte le chemin selon besoin
            allow_origin: ['^https?://localhost(:[0-9]+)?$', '^https?://magi.localhost$']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'X-CSRF-TOKEN']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
            max_age: 3600
