<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250822224800 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, price NUMERIC(12, 2) DEFAULT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, average_rating NUMERIC(4, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, address_id INT DEFAULT NULL, company_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_AC74095AF5B7AF75 ON activity (address_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_AC74095A979B1AD6 ON activity (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE activity_category (activity_id INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY(activity_id, category_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A646A9CF81C06096 ON activity_category (activity_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A646A9CF12469DE2 ON activity_category (category_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE activity_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_url VARCHAR(255) NOT NULL, is_main BOOLEAN NOT NULL, activity_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_DB3F32EC81C06096 ON activity_image (activity_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE address (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, street VARCHAR(255) NOT NULL, city VARCHAR(120) NOT NULL, postal_code VARCHAR(120) DEFAULT NULL, country VARCHAR(120) NOT NULL, country_code VARCHAR(2) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, geom POINT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, table_name VARCHAR(120) NOT NULL, record_pk VARCHAR(120) NOT NULL, action VARCHAR(20) NOT NULL, diff JSON DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_F6E1C0F5A76ED395 ON audit_log (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, bookable_id INT NOT NULL, start_date TIMESTAMP(0) WITH TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITH TIME ZONE NOT NULL, is_available BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE calendar_sync_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(40) NOT NULL, access_token TEXT NOT NULL, refresh_token TEXT DEFAULT NULL, scope TEXT DEFAULT NULL, synced_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8A8C7CA9A76ED395 ON calendar_sync_account (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, visibility_boost INT DEFAULT 0 NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_64C19C1727ACA70 ON category (parent_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, post_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9474526C4B89032C ON comment (post_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9474526CF675F31B ON comment (author_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE commission_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rate_percent NUMERIC(5, 2) DEFAULT 10 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, company_id INT NOT NULL, category_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_3496B2E979B1AD6 ON commission_rule (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_3496B2E12469DE2 ON commission_rule (category_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, tax_id VARCHAR(100) DEFAULT NULL, locale VARCHAR(255) DEFAULT 'fr_FR' NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE company_feature_flag (enabled BOOLEAN DEFAULT true NOT NULL, company_id INT NOT NULL, flag_key VARCHAR(80) NOT NULL, PRIMARY KEY(company_id, flag_key))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_7D13AE27979B1AD6 ON company_feature_flag (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_7D13AE2731B54A29 ON company_feature_flag (flag_key)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE document_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, form_data JSON NOT NULL, generated_pdf_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, template_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9FF82943A76ED395 ON document_request (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9FF829435DA0FB8 ON document_request (template_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE document_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, type VARCHAR(50) NOT NULL, locale VARCHAR(10) NOT NULL, version INT DEFAULT 1 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, form_schema JSON NOT NULL, form_data JSON NOT NULL, generated_pdf_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, owner_company_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_18A1EEDAC5F18393 ON document_template (owner_company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, rental_price_per_day NUMERIC(12, 2) DEFAULT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, start_datetime TIMESTAMP(0) WITH TIME ZONE NOT NULL, end_datetime TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, price NUMERIC(12, 2) DEFAULT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, max_guests INT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT 'now()' NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT 'now()' NOT NULL, organizer_id INT DEFAULT NULL, venue_id INT DEFAULT NULL, company_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_3BAE0AA7876C4DDA ON event (organizer_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_3BAE0AA740A73EBA ON event (venue_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_3BAE0AA7979B1AD6 ON event (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE event_booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, booking_date TIMESTAMP(0) WITH TIME ZONE NOT NULL, total_amount NUMERIC(12, 2) DEFAULT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, event_id INT DEFAULT NULL, booker_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_655B447171F7E88B ON event_booking (event_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_655B44718B7E4006 ON event_booking (booker_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE event_booking_equipment (event_booking_id INT NOT NULL, equipment_id INT NOT NULL, PRIMARY KEY(event_booking_id, equipment_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D59344E15BDEC54F ON event_booking_equipment (event_booking_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D59344E1517FE9FE ON event_booking_equipment (equipment_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE feature_flag (key VARCHAR(80) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(key))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE guest (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, email VARCHAR(120) DEFAULT NULL, phone VARCHAR(30) DEFAULT NULL, invitation_status VARCHAR(255) NOT NULL, event_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_ACB79A3571F7E88B ON guest (event_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE invoice (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, invoice_number VARCHAR(80) NOT NULL, issue_date TIMESTAMP(0) WITH TIME ZONE NOT NULL, due_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, total_amount NUMERIC(12, 2) NOT NULL, total_taxes NUMERIC(12, 2) DEFAULT 0 NOT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, status VARCHAR(255) NOT NULL, locale VARCHAR(10) DEFAULT 'fr_FR' NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT 'now()' NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT 'now()' NOT NULL, client_id INT DEFAULT NULL, provider_id INT DEFAULT NULL, company_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_906517442DA68207 ON invoice (invoice_number)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9065174419EB6921 ON invoice (client_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_90651744A53A8AA ON invoice (provider_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_90651744979B1AD6 ON invoice (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE invoice_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(255) DEFAULT NULL, quantity NUMERIC(12, 2) NOT NULL, unit_price NUMERIC(12, 2) NOT NULL, total NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT 'now()' NOT NULL, tax_rate_id INT DEFAULT NULL, invoice_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1DDE477BFDD13F95 ON invoice_item (tax_rate_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1DDE477B2989F1FD ON invoice_item (invoice_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE kpi_metric (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, value NUMERIC(12, 2) NOT NULL, unit VARCHAR(20) DEFAULT NULL, period_start TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, period_end TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, company_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1603F9AAA76ED395 ON kpi_metric (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1603F9AA979B1AD6 ON kpi_metric (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE lease (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITH TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, rent_amount NUMERIC(12, 2) DEFAULT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, property_id INT DEFAULT NULL, tenant_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_E6C77495549213EC ON lease (property_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_E6C774959033212A ON lease (tenant_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE message_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, channel VARCHAR(20) NOT NULL, subject VARCHAR(200) DEFAULT NULL, body TEXT NOT NULL, locale VARCHAR(10) DEFAULT 'fr_FR' NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, channel VARCHAR(20) NOT NULL, payload JSON DEFAULT NULL, status VARCHAR(20) DEFAULT 'queued' NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, sent_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, template_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_BF5476CA5DA0FB8 ON notification (template_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, method VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, transaction_id VARCHAR(100) DEFAULT NULL, paid_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, invoice_id INT DEFAULT NULL, payer_id INT DEFAULT NULL, reservation_id INT DEFAULT NULL, event_booking_id INT DEFAULT NULL, provider_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6D28840D2989F1FD ON payment (invoice_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6D28840DC17AD9A9 ON payment (payer_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6D28840DB83297E7 ON payment (reservation_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_6D28840D5BDEC54F ON payment (event_booking_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6D28840DA53A8AA ON payment (provider_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE payment_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_account_id VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, company_id INT DEFAULT NULL, provider_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_647F584EA76ED395 ON payment_account (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_647F584E979B1AD6 ON payment_account (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_647F584EA53A8AA ON payment_account (provider_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE payment_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(255) NOT NULL, payload JSON DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, payment_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6CE73C154C3A3BB ON payment_event (payment_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE payment_provider (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(80) NOT NULL, type VARCHAR(50) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, config JSON DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE payout (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, status VARCHAR(255) NOT NULL, external_transfer_id VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, paid_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, company_id INT DEFAULT NULL, supplier_id INT DEFAULT NULL, provider_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_4E2EA902979B1AD6 ON payout (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_4E2EA9022ADD6D8C ON payout (supplier_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_4E2EA902A53A8AA ON payout (provider_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, summary VARCHAR(255) NOT NULL, content TEXT NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5A8A6C8DF675F31B ON post (author_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE post_tag (post_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY(post_id, tag_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5ACE3AF04B89032C ON post_tag (post_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5ACE3AF0BAD26311 ON post_tag (tag_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE property (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, price NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, surface NUMERIC(12, 2) NOT NULL, is_visible BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, address_id INT NOT NULL, owner_id INT NOT NULL, company_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8BF21CDEF5B7AF75 ON property (address_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8BF21CDE7E3C61F9 ON property (owner_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8BF21CDE979B1AD6 ON property (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE property_category (property_id INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY(property_id, category_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_58CB2D85549213EC ON property_category (property_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_58CB2D8512469DE2 ON property_category (category_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE property_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, is_main BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, property_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_32EC552549213EC ON property_image (property_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE refund (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(12, 2) NOT NULL, reason TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, processed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, payment_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_5B2C14584C3A3BB ON refund (payment_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE rent_payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, method VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, receipt_path VARCHAR(255) DEFAULT NULL, due_date TIMESTAMP(0) WITH TIME ZONE NOT NULL, paid_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT 'now()' NOT NULL, lease_id INT DEFAULT NULL, tenant_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8C04FF7DD3CA542C ON rent_payment (lease_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8C04FF7D9033212A ON rent_payment (tenant_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, bookable_id INT NOT NULL, start_date TIMESTAMP(0) WITH TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITH TIME ZONE NOT NULL, total_amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, average_rating NUMERIC(4, 2) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_42C84955A76ED395 ON reservation (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, reviewable_id INT NOT NULL, rating SMALLINT NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, reviewer_id INT NOT NULL, reservation_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_794381C670574616 ON review (reviewer_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_794381C6B83297E7 ON review (reservation_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX ux_review_res_reviewer ON review (reservation_id, reviewer_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE service_area (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, polygon POLYGON DEFAULT NULL, city VARCHAR(120) DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, supplier_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_19D789842ADD6D8C ON service_area (supplier_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, interval VARCHAR(20) DEFAULT 'month' NOT NULL, started_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, company_id INT NOT NULL, plan_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A3C664D3979B1AD6 ON subscription (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A3C664D3E899029B ON subscription (plan_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE subscription_plan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, price NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, features JSON NOT NULL, interval VARCHAR(20) DEFAULT 'month' NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE supplier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, company_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9B2A6C7EA76ED395 ON supplier (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9B2A6C7E979B1AD6 ON supplier (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE supplier_category (supplier_id INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY(supplier_id, category_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8BC571402ADD6D8C ON supplier_category (supplier_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8BC5714012469DE2 ON supplier_category (category_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE supplier_service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, price NUMERIC(12, 2) DEFAULT NULL, currency VARCHAR(3) DEFAULT 'EUR' NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, supplier_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_60F8EECD2ADD6D8C ON supplier_service (supplier_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_389B7835E237E06 ON tag (name)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE tax_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, rate_percent NUMERIC(5, 2) NOT NULL, country_code VARCHAR(2) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE time_slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, bookable_id INT NOT NULL, start_time TIMESTAMP(0) WITH TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITH TIME ZONE NOT NULL, is_recurring BOOLEAN DEFAULT false NOT NULL, exception BOOLEAN DEFAULT false NOT NULL, rrule TEXT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE user_hub (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(255) NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, locale VARCHAR(10) DEFAULT 'fr_FR' NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, address_id INT DEFAULT NULL, company_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_A367AFC6F85E0677 ON user_hub (username)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_A367AFC6E7927C74 ON user_hub (email)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A367AFC6F5B7AF75 ON user_hub (address_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A367AFC6979B1AD6 ON user_hub (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE venue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, capacity INT DEFAULT NULL, price_per_hour NUMERIC(12, 2) DEFAULT NULL, currency VARCHAR(3) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT 'now()' NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT 'now()' NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, owner_id INT DEFAULT NULL, address_id INT DEFAULT NULL, company_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_91911B0D7E3C61F9 ON venue (owner_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_91911B0DF5B7AF75 ON venue (address_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_91911B0D979B1AD6 ON venue (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE venue_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_url VARCHAR(255) NOT NULL, is_main BOOLEAN NOT NULL, venue_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1D86098840A73EBA ON venue_image (venue_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE webhook_endpoint (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, secret VARCHAR(255) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, company_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_3AB88953979B1AD6 ON webhook_endpoint (company_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE webhook_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, payload_json JSON DEFAULT NULL, response_status VARCHAR(10) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE activity ADD CONSTRAINT FK_AC74095AF5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE activity ADD CONSTRAINT FK_AC74095A979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE activity_category ADD CONSTRAINT FK_A646A9CF81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE activity_category ADD CONSTRAINT FK_A646A9CF12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE activity_image ADD CONSTRAINT FK_DB3F32EC81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE audit_log ADD CONSTRAINT FK_F6E1C0F5A76ED395 FOREIGN KEY (user_id) REFERENCES user_hub (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE calendar_sync_account ADD CONSTRAINT FK_8A8C7CA9A76ED395 FOREIGN KEY (user_id) REFERENCES user_hub (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE category ADD CONSTRAINT FK_64C19C1727ACA70 FOREIGN KEY (parent_id) REFERENCES category (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE comment ADD CONSTRAINT FK_9474526C4B89032C FOREIGN KEY (post_id) REFERENCES post (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE comment ADD CONSTRAINT FK_9474526CF675F31B FOREIGN KEY (author_id) REFERENCES user_hub (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE commission_rule ADD CONSTRAINT FK_3496B2E979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE commission_rule ADD CONSTRAINT FK_3496B2E12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE company_feature_flag ADD CONSTRAINT FK_7D13AE27979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE company_feature_flag ADD CONSTRAINT FK_7D13AE2731B54A29 FOREIGN KEY (flag_key) REFERENCES feature_flag (key) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_request ADD CONSTRAINT FK_9FF82943A76ED395 FOREIGN KEY (user_id) REFERENCES user_hub (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_request ADD CONSTRAINT FK_9FF829435DA0FB8 FOREIGN KEY (template_id) REFERENCES document_template (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_template ADD CONSTRAINT FK_18A1EEDAC5F18393 FOREIGN KEY (owner_company_id) REFERENCES company (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7876C4DDA FOREIGN KEY (organizer_id) REFERENCES user_hub (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA740A73EBA FOREIGN KEY (venue_id) REFERENCES venue (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event_booking ADD CONSTRAINT FK_655B447171F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event_booking ADD CONSTRAINT FK_655B44718B7E4006 FOREIGN KEY (booker_id) REFERENCES user_hub (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event_booking_equipment ADD CONSTRAINT FK_D59344E15BDEC54F FOREIGN KEY (event_booking_id) REFERENCES event_booking (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event_booking_equipment ADD CONSTRAINT FK_D59344E1517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE guest ADD CONSTRAINT FK_ACB79A3571F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invoice ADD CONSTRAINT FK_9065174419EB6921 FOREIGN KEY (client_id) REFERENCES user_hub (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invoice ADD CONSTRAINT FK_90651744A53A8AA FOREIGN KEY (provider_id) REFERENCES user_hub (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invoice ADD CONSTRAINT FK_90651744979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invoice_item ADD CONSTRAINT FK_1DDE477BFDD13F95 FOREIGN KEY (tax_rate_id) REFERENCES tax_rate (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invoice_item ADD CONSTRAINT FK_1DDE477B2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE kpi_metric ADD CONSTRAINT FK_1603F9AAA76ED395 FOREIGN KEY (user_id) REFERENCES user_hub (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE kpi_metric ADD CONSTRAINT FK_1603F9AA979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE lease ADD CONSTRAINT FK_E6C77495549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE lease ADD CONSTRAINT FK_E6C774959033212A FOREIGN KEY (tenant_id) REFERENCES user_hub (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES user_hub (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA5DA0FB8 FOREIGN KEY (template_id) REFERENCES message_template (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment ADD CONSTRAINT FK_6D28840D2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment ADD CONSTRAINT FK_6D28840DC17AD9A9 FOREIGN KEY (payer_id) REFERENCES user_hub (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment ADD CONSTRAINT FK_6D28840DB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment ADD CONSTRAINT FK_6D28840D5BDEC54F FOREIGN KEY (event_booking_id) REFERENCES event_booking (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment ADD CONSTRAINT FK_6D28840DA53A8AA FOREIGN KEY (provider_id) REFERENCES payment_provider (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment_account ADD CONSTRAINT FK_647F584EA76ED395 FOREIGN KEY (user_id) REFERENCES user_hub (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment_account ADD CONSTRAINT FK_647F584E979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment_account ADD CONSTRAINT FK_647F584EA53A8AA FOREIGN KEY (provider_id) REFERENCES payment_provider (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment_event ADD CONSTRAINT FK_6CE73C154C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payout ADD CONSTRAINT FK_4E2EA902979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payout ADD CONSTRAINT FK_4E2EA9022ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payout ADD CONSTRAINT FK_4E2EA902A53A8AA FOREIGN KEY (provider_id) REFERENCES payment_provider (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DF675F31B FOREIGN KEY (author_id) REFERENCES user_hub (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE post_tag ADD CONSTRAINT FK_5ACE3AF04B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE post_tag ADD CONSTRAINT FK_5ACE3AF0BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE property ADD CONSTRAINT FK_8BF21CDEF5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE property ADD CONSTRAINT FK_8BF21CDE7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user_hub (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE property ADD CONSTRAINT FK_8BF21CDE979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE property_category ADD CONSTRAINT FK_58CB2D85549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE property_category ADD CONSTRAINT FK_58CB2D8512469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE property_image ADD CONSTRAINT FK_32EC552549213EC FOREIGN KEY (property_id) REFERENCES property (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE refund ADD CONSTRAINT FK_5B2C14584C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE rent_payment ADD CONSTRAINT FK_8C04FF7DD3CA542C FOREIGN KEY (lease_id) REFERENCES lease (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE rent_payment ADD CONSTRAINT FK_8C04FF7D9033212A FOREIGN KEY (tenant_id) REFERENCES user_hub (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reservation ADD CONSTRAINT FK_42C84955A76ED395 FOREIGN KEY (user_id) REFERENCES user_hub (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE review ADD CONSTRAINT FK_794381C670574616 FOREIGN KEY (reviewer_id) REFERENCES user_hub (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE review ADD CONSTRAINT FK_794381C6B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE service_area ADD CONSTRAINT FK_19D789842ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3E899029B FOREIGN KEY (plan_id) REFERENCES subscription_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supplier ADD CONSTRAINT FK_9B2A6C7EA76ED395 FOREIGN KEY (user_id) REFERENCES user_hub (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supplier ADD CONSTRAINT FK_9B2A6C7E979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supplier_category ADD CONSTRAINT FK_8BC571402ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supplier_category ADD CONSTRAINT FK_8BC5714012469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supplier_service ADD CONSTRAINT FK_60F8EECD2ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_hub ADD CONSTRAINT FK_A367AFC6F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_hub ADD CONSTRAINT FK_A367AFC6979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE venue ADD CONSTRAINT FK_91911B0D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user_hub (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE venue ADD CONSTRAINT FK_91911B0DF5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE venue ADD CONSTRAINT FK_91911B0D979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE venue_image ADD CONSTRAINT FK_1D86098840A73EBA FOREIGN KEY (venue_id) REFERENCES venue (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE webhook_endpoint ADD CONSTRAINT FK_3AB88953979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE activity DROP CONSTRAINT FK_AC74095AF5B7AF75
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE activity DROP CONSTRAINT FK_AC74095A979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE activity_category DROP CONSTRAINT FK_A646A9CF81C06096
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE activity_category DROP CONSTRAINT FK_A646A9CF12469DE2
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE activity_image DROP CONSTRAINT FK_DB3F32EC81C06096
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE audit_log DROP CONSTRAINT FK_F6E1C0F5A76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE calendar_sync_account DROP CONSTRAINT FK_8A8C7CA9A76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE category DROP CONSTRAINT FK_64C19C1727ACA70
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE comment DROP CONSTRAINT FK_9474526C4B89032C
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE comment DROP CONSTRAINT FK_9474526CF675F31B
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE commission_rule DROP CONSTRAINT FK_3496B2E979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE commission_rule DROP CONSTRAINT FK_3496B2E12469DE2
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE company_feature_flag DROP CONSTRAINT FK_7D13AE27979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE company_feature_flag DROP CONSTRAINT FK_7D13AE2731B54A29
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_request DROP CONSTRAINT FK_9FF82943A76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_request DROP CONSTRAINT FK_9FF829435DA0FB8
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_template DROP CONSTRAINT FK_18A1EEDAC5F18393
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7876C4DDA
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA740A73EBA
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event_booking DROP CONSTRAINT FK_655B447171F7E88B
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event_booking DROP CONSTRAINT FK_655B44718B7E4006
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event_booking_equipment DROP CONSTRAINT FK_D59344E15BDEC54F
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE event_booking_equipment DROP CONSTRAINT FK_D59344E1517FE9FE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE guest DROP CONSTRAINT FK_ACB79A3571F7E88B
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invoice DROP CONSTRAINT FK_9065174419EB6921
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invoice DROP CONSTRAINT FK_90651744A53A8AA
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invoice DROP CONSTRAINT FK_90651744979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invoice_item DROP CONSTRAINT FK_1DDE477BFDD13F95
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE invoice_item DROP CONSTRAINT FK_1DDE477B2989F1FD
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE kpi_metric DROP CONSTRAINT FK_1603F9AAA76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE kpi_metric DROP CONSTRAINT FK_1603F9AA979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE lease DROP CONSTRAINT FK_E6C77495549213EC
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE lease DROP CONSTRAINT FK_E6C774959033212A
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA5DA0FB8
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment DROP CONSTRAINT FK_6D28840D2989F1FD
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment DROP CONSTRAINT FK_6D28840DC17AD9A9
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment DROP CONSTRAINT FK_6D28840DB83297E7
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment DROP CONSTRAINT FK_6D28840D5BDEC54F
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment DROP CONSTRAINT FK_6D28840DA53A8AA
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment_account DROP CONSTRAINT FK_647F584EA76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment_account DROP CONSTRAINT FK_647F584E979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment_account DROP CONSTRAINT FK_647F584EA53A8AA
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payment_event DROP CONSTRAINT FK_6CE73C154C3A3BB
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payout DROP CONSTRAINT FK_4E2EA902979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payout DROP CONSTRAINT FK_4E2EA9022ADD6D8C
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE payout DROP CONSTRAINT FK_4E2EA902A53A8AA
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8DF675F31B
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE post_tag DROP CONSTRAINT FK_5ACE3AF04B89032C
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE post_tag DROP CONSTRAINT FK_5ACE3AF0BAD26311
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE property DROP CONSTRAINT FK_8BF21CDEF5B7AF75
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE property DROP CONSTRAINT FK_8BF21CDE7E3C61F9
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE property DROP CONSTRAINT FK_8BF21CDE979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE property_category DROP CONSTRAINT FK_58CB2D85549213EC
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE property_category DROP CONSTRAINT FK_58CB2D8512469DE2
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE property_image DROP CONSTRAINT FK_32EC552549213EC
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE refund DROP CONSTRAINT FK_5B2C14584C3A3BB
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE rent_payment DROP CONSTRAINT FK_8C04FF7DD3CA542C
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE rent_payment DROP CONSTRAINT FK_8C04FF7D9033212A
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE reservation DROP CONSTRAINT FK_42C84955A76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE review DROP CONSTRAINT FK_794381C670574616
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE review DROP CONSTRAINT FK_794381C6B83297E7
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE service_area DROP CONSTRAINT FK_19D789842ADD6D8C
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D3979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D3E899029B
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supplier DROP CONSTRAINT FK_9B2A6C7EA76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supplier DROP CONSTRAINT FK_9B2A6C7E979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supplier_category DROP CONSTRAINT FK_8BC571402ADD6D8C
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supplier_category DROP CONSTRAINT FK_8BC5714012469DE2
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supplier_service DROP CONSTRAINT FK_60F8EECD2ADD6D8C
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_hub DROP CONSTRAINT FK_A367AFC6F5B7AF75
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_hub DROP CONSTRAINT FK_A367AFC6979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE venue DROP CONSTRAINT FK_91911B0D7E3C61F9
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE venue DROP CONSTRAINT FK_91911B0DF5B7AF75
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE venue DROP CONSTRAINT FK_91911B0D979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE venue_image DROP CONSTRAINT FK_1D86098840A73EBA
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE webhook_endpoint DROP CONSTRAINT FK_3AB88953979B1AD6
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE activity
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE activity_category
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE activity_image
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE address
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE audit_log
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE availability
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE calendar_sync_account
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE category
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE comment
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE commission_rule
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE company
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE company_feature_flag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE document_request
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE document_template
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE equipment
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE event
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE event_booking
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE event_booking_equipment
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE feature_flag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE guest
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE invoice
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE invoice_item
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE kpi_metric
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE lease
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE message_template
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE notification
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE payment
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE payment_account
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE payment_event
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE payment_provider
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE payout
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE post
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE post_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE property
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE property_category
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE property_image
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE refund
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE rent_payment
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE reservation
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE review
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE service_area
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE subscription
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE subscription_plan
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE supplier
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE supplier_category
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE supplier_service
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE tax_rate
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE time_slot
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE user_hub
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE venue
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE venue_image
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE webhook_endpoint
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE webhook_log
        SQL);
    }
}
