# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.locale: 'en'
    app.notifications.email_sender: anonymous@example.com
    app.api_url: '%env(APP_API_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            # this allows to define the scalar arguments once and apply them to any services
            # defined/created in this file; if some argument is used rarely, instead of defining
            # it here you can use the #[Autowire] attribute to inject it manually in the service constructor
            array $enabledLocales: '%kernel.enabled_locales%'
            string $defaultLocale: '%app.locale%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\PdfGenerator: ~
    App\Controller\DocumentRequestPdfController:
        arguments:
            $repository: '@App\Repository\DocumentRequestRepository'
            $pdfGenerator: '@App\Service\PdfGenerator'

    App\Controller\InvoicePdfController:
        arguments:
            $invoiceRepository: '@App\Repository\InvoiceRepository'
            $pdfGenerator: '@App\Service\PdfGenerator'

    App\Controller\PropertyPdfController:
        arguments:
            $propertyRepository: '@App\Repository\PropertyRepository'
            $pdfGenerator: '@App\Service\PdfGenerator'

    App\Service\FileUploader:
        arguments:
            $uploadsPath: '%kernel.project_dir%/public/uploads/receipts'

    App\Service\ReservationProcessor:
        arguments:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'

    App\Validator\Constraints\PostalCodeByCountryValidator:
        tags: [ 'validator.constraint_validator' ]
